add config file
ncf-ds/chloroform pull request #2
Opened 2016-10-31 00:52 UTC by meteor-man

2016-11-01 13:42 UTC, qhool requested changes

2016-11-01 13:42 UTC, qhool commented on utils/config.py
> +@author: salami
The number of monikers you have is confusing.

2016-11-01 13:42 UTC, qhool commented on utils/config.py
> +Created on Oct 29, 2016
This file should have the word `default` in the name.

2016-11-01 13:42 UTC, qhool commented on models/database.py
> +app.config['SQLALCHEMY_DATABASE_URI'] = config.SQLALCHEMY_DATABASE_URI
It would be better to follow [this example from the flask docs](http://flask.pocoo.org/docs/0.11/config/#development-production)

2016-11-01 18:49 UTC, meteor-man commented
Reviews applied.

2016-11-02 01:40 UTC, qhool approved these changes

2016-11-02 01:40 UTC, qhool commented
You're still only copying the one parameter from the default config, but we can fix this later.

2016-11-05 23:00 UTC, merged